/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * KitchenSpurs API
 * API documentation for KitchenSpurs restaurant management application
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetApiCuisines200,
  GetApiCuisinesId200
} from '../kitchenSpursAPI.schemas';


/**
 * @summary Get all cuisines
 */
export type getApiCuisinesResponse200 = {
  data: GetApiCuisines200
  status: 200
}
    
export type getApiCuisinesResponseSuccess = (getApiCuisinesResponse200) & {
  headers: Headers;
};
;

export type getApiCuisinesResponse = (getApiCuisinesResponseSuccess)

export const getGetApiCuisinesUrl = () => {


  

  return `http://localhost:8000/api/cuisines`
}

export const getApiCuisines = async ( options?: RequestInit): Promise<getApiCuisinesResponse> => {
  
  const res = await fetch(getGetApiCuisinesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiCuisinesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiCuisinesResponse
}


/**
 * @summary Get cuisine by ID
 */
export type getApiCuisinesIdResponse200 = {
  data: GetApiCuisinesId200
  status: 200
}

export type getApiCuisinesIdResponse404 = {
  data: void
  status: 404
}
    
export type getApiCuisinesIdResponseSuccess = (getApiCuisinesIdResponse200) & {
  headers: Headers;
};
export type getApiCuisinesIdResponseError = (getApiCuisinesIdResponse404) & {
  headers: Headers;
};

export type getApiCuisinesIdResponse = (getApiCuisinesIdResponseSuccess | getApiCuisinesIdResponseError)

export const getGetApiCuisinesIdUrl = (id: number,) => {


  

  return `http://localhost:8000/api/cuisines/${id}`
}

export const getApiCuisinesId = async (id: number, options?: RequestInit): Promise<getApiCuisinesIdResponse> => {
  
  const res = await fetch(getGetApiCuisinesIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiCuisinesIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiCuisinesIdResponse
}


