/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * KitchenSpurs API
 * API documentation for KitchenSpurs restaurant management application
 * OpenAPI spec version: 1.0.0
 */
export interface Cuisine {
  id?: number;
  name?: string;
  slug?: string;
  /** @nullable */
  description?: string | null;
}

export interface Location {
  id?: number;
  name?: string;
  slug?: string;
}

export interface Restaurant {
  id?: number;
  name?: string;
  address?: string;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  email?: string | null;
  location_id?: number;
  cuisine_id?: number;
  /** @nullable */
  revenue?: number | null;
  location?: Location;
  cuisine?: Cuisine;
}

export interface Order {
  id?: number;
  restaurant_id?: number;
  order_amount?: number;
  order_time?: string;
}

export interface PaginationMeta {
  current_page?: number;
  from?: number;
  last_page?: number;
  per_page?: number;
  to?: number;
  total?: number;
}

export type GetApiLocations200 = {
  status?: boolean;
  message?: string;
  data?: Location[];
};

export type GetApiCuisines200 = {
  status?: boolean;
  message?: string;
  data?: Cuisine[];
};

export type GetApiCuisinesId200 = {
  status?: boolean;
  message?: string;
  data?: Cuisine;
};

export type PostApiRestaurantsBodySortBy = typeof PostApiRestaurantsBodySortBy[keyof typeof PostApiRestaurantsBodySortBy];


export const PostApiRestaurantsBodySortBy = {
  name: 'name',
  revenue: 'revenue',
} as const;

export type PostApiRestaurantsBodySortDirection = typeof PostApiRestaurantsBodySortDirection[keyof typeof PostApiRestaurantsBodySortDirection];


export const PostApiRestaurantsBodySortDirection = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type PostApiRestaurantsBody = {
  page?: number;
  search?: string;
  location?: string;
  cuisine?: string;
  sort_by?: PostApiRestaurantsBodySortBy;
  sort_direction?: PostApiRestaurantsBodySortDirection;
  from?: string;
  to?: string;
};

export type PostApiRestaurants200Data = {
  current_page?: number;
  data?: Restaurant[];
  total?: number;
  per_page?: number;
};

export type PostApiRestaurants200 = {
  status?: boolean;
  message?: string;
  data?: PostApiRestaurants200Data;
};

export type GetApiRestaurantsId200 = {
  status?: boolean;
  message?: string;
  data?: Restaurant;
};

export type GetApiRestaurantsIdTrendsParams = {
from?: string;
to?: string;
};

export type GetApiRestaurantsIdTrends200DataPeakHours = { [key: string]: unknown };

export type GetApiRestaurantsIdTrends200Data = {
  total_orders?: number;
  total_revenue?: number;
  average_order_value?: number;
  peak_hours?: GetApiRestaurantsIdTrends200DataPeakHours;
};

export type GetApiRestaurantsIdTrends200 = {
  status?: boolean;
  message?: string;
  data?: GetApiRestaurantsIdTrends200Data;
};

export type PostApiRestaurantsIdOrdersBody = {
  page?: number;
  from?: string;
  to?: string;
  min_amount?: number;
  max_amount?: number;
};

export type PostApiRestaurantsIdOrders200Data = {
  current_page?: number;
  data?: Order[];
  total?: number;
  per_page?: number;
};

export type PostApiRestaurantsIdOrders200 = {
  status?: boolean;
  message?: string;
  data?: PostApiRestaurantsIdOrders200Data;
};

export type PostApiOrdersBody = {
  page?: number;
  restaurant_id?: number;
  from?: string;
  to?: string;
  min_amount?: number;
  max_amount?: number;
};

export type PostApiOrders200Data = {
  current_page?: number;
  data?: Order[];
  total?: number;
  per_page?: number;
};

export type PostApiOrders200 = {
  status?: boolean;
  message?: string;
  data?: PostApiOrders200Data;
};

