/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * KitchenSpurs API
 * API documentation for KitchenSpurs restaurant management application
 * OpenAPI spec version: 1.0.0
 */
import type {
  PostApiOrders200,
  PostApiOrdersBody
} from '../kitchenSpursAPI.schemas';


/**
 * @summary Get all orders with filters and pagination
 */
export type postApiOrdersResponse200 = {
  data: PostApiOrders200
  status: 200
}
    
export type postApiOrdersResponseSuccess = (postApiOrdersResponse200) & {
  headers: Headers;
};
;

export type postApiOrdersResponse = (postApiOrdersResponseSuccess)

export const getPostApiOrdersUrl = () => {


  

  return `http://localhost:8000/api/orders`
}

export const postApiOrders = async (postApiOrdersBody: PostApiOrdersBody, options?: RequestInit): Promise<postApiOrdersResponse> => {
  
  const res = await fetch(getPostApiOrdersUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiOrdersBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiOrdersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiOrdersResponse
}


