/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * KitchenSpurs API
 * API documentation for KitchenSpurs restaurant management application
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetApiLocations200
} from '../kitchenSpursAPI.schemas';


/**
 * @summary Get all locations
 */
export type getApiLocationsResponse200 = {
  data: GetApiLocations200
  status: 200
}
    
export type getApiLocationsResponseSuccess = (getApiLocationsResponse200) & {
  headers: Headers;
};
;

export type getApiLocationsResponse = (getApiLocationsResponseSuccess)

export const getGetApiLocationsUrl = () => {


  

  return `http://localhost:8000/api/locations`
}

export const getApiLocations = async ( options?: RequestInit): Promise<getApiLocationsResponse> => {
  
  const res = await fetch(getGetApiLocationsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiLocationsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiLocationsResponse
}


