/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * KitchenSpurs API
 * API documentation for KitchenSpurs restaurant management application
 * OpenAPI spec version: 1.0.0
 */

export type getApiResponse200 = {
  data: void
  status: 200
}
    
export type getApiResponseSuccess = (getApiResponse200) & {
  headers: Headers;
};
;

export type getApiResponse = (getApiResponseSuccess)

export const getGetApiUrl = () => {


  

  return `http://localhost:8000/api`
}

export const getApi = async ( options?: RequestInit): Promise<getApiResponse> => {
  
  const res = await fetch(getGetApiUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiResponse
}


