/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * KitchenSpurs API
 * API documentation for KitchenSpurs restaurant management application
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetApiRestaurantsId200,
  GetApiRestaurantsIdTrends200,
  GetApiRestaurantsIdTrendsParams,
  PostApiRestaurants200,
  PostApiRestaurantsBody,
  PostApiRestaurantsIdOrders200,
  PostApiRestaurantsIdOrdersBody
} from '../kitchenSpursAPI.schemas';


/**
 * @summary Get restaurants with pagination and filters
 */
export type postApiRestaurantsResponse200 = {
  data: PostApiRestaurants200
  status: 200
}
    
export type postApiRestaurantsResponseSuccess = (postApiRestaurantsResponse200) & {
  headers: Headers;
};
;

export type postApiRestaurantsResponse = (postApiRestaurantsResponseSuccess)

export const getPostApiRestaurantsUrl = () => {


  

  return `http://localhost:8000/api/restaurants`
}

export const postApiRestaurants = async (postApiRestaurantsBody?: PostApiRestaurantsBody, options?: RequestInit): Promise<postApiRestaurantsResponse> => {
  
  const res = await fetch(getPostApiRestaurantsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiRestaurantsBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiRestaurantsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiRestaurantsResponse
}


export type getApiRestaurantsIdResponse200 = {
  data: GetApiRestaurantsId200
  status: 200
}
    
export type getApiRestaurantsIdResponseSuccess = (getApiRestaurantsIdResponse200) & {
  headers: Headers;
};
;

export type getApiRestaurantsIdResponse = (getApiRestaurantsIdResponseSuccess)

export const getGetApiRestaurantsIdUrl = (id: number,) => {


  

  return `http://localhost:8000/api/restaurants/${id}`
}

export const getApiRestaurantsId = async (id: number, options?: RequestInit): Promise<getApiRestaurantsIdResponse> => {
  
  const res = await fetch(getGetApiRestaurantsIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiRestaurantsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiRestaurantsIdResponse
}


/**
 * @summary Get order trends for a restaurant
 */
export type getApiRestaurantsIdTrendsResponse200 = {
  data: GetApiRestaurantsIdTrends200
  status: 200
}
    
export type getApiRestaurantsIdTrendsResponseSuccess = (getApiRestaurantsIdTrendsResponse200) & {
  headers: Headers;
};
;

export type getApiRestaurantsIdTrendsResponse = (getApiRestaurantsIdTrendsResponseSuccess)

export const getGetApiRestaurantsIdTrendsUrl = (id: number,
    params?: GetApiRestaurantsIdTrendsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/api/restaurants/${id}/trends?${stringifiedParams}` : `http://localhost:8000/api/restaurants/${id}/trends`
}

export const getApiRestaurantsIdTrends = async (id: number,
    params?: GetApiRestaurantsIdTrendsParams, options?: RequestInit): Promise<getApiRestaurantsIdTrendsResponse> => {
  
  const res = await fetch(getGetApiRestaurantsIdTrendsUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiRestaurantsIdTrendsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiRestaurantsIdTrendsResponse
}


/**
 * @summary Get orders for a specific restaurant
 */
export type postApiRestaurantsIdOrdersResponse200 = {
  data: PostApiRestaurantsIdOrders200
  status: 200
}
    
export type postApiRestaurantsIdOrdersResponseSuccess = (postApiRestaurantsIdOrdersResponse200) & {
  headers: Headers;
};
;

export type postApiRestaurantsIdOrdersResponse = (postApiRestaurantsIdOrdersResponseSuccess)

export const getPostApiRestaurantsIdOrdersUrl = (id: number,) => {


  

  return `http://localhost:8000/api/restaurants/${id}/orders`
}

export const postApiRestaurantsIdOrders = async (id: number,
    postApiRestaurantsIdOrdersBody: PostApiRestaurantsIdOrdersBody, options?: RequestInit): Promise<postApiRestaurantsIdOrdersResponse> => {
  
  const res = await fetch(getPostApiRestaurantsIdOrdersUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiRestaurantsIdOrdersBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiRestaurantsIdOrdersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiRestaurantsIdOrdersResponse
}


